language: node_js
before_script:
  # Update apt repos
  - sudo apt-get update
  # Install command needed for node-gm (image resize)
  - sudo apt-get install graphicsmagick
script:
  - date
  - npm install -g bloginator
  - bloginate
deploy:
  - provider: s3
    access_key_id: AKIAJQOIHIYLDTKP2YWQ
    secret_access_key:
      secure: kBOw3vhU6xaahgXHRTdtjVZdLXd9wPCiucGhfCpAMTmyTmJP0SalYqoCda5QNujnG/EsQNBklhgSW3WlfYGbIQ389dt5x6fyQ/vKj2IHMa0xgfGWGCnSLT6VVRmNDAL6Lkp1g5br/wAh2HZlesBnli7CED7bv/CVyanOUHb3yHupFgvcgB0iLoi+RgXq6dv/ysP6vCLH/IBzwd2BZxX8dcEilkR26cGfVkLbIYdP/TQGAQJou//+bLAHW2CL2unTBMXPEQXeiCbFwPgPlCCOhkYzwC5S/1nfC8vIWU0YL9B4Dmx1F2f7RXDnox/7heU2Ng0CxDRFMWLN2Yd0rfxVPeSbdpt2Dn5lF+gCA6Zfyl+iEaUsxM+qwyuM5xlnHNUATftphZg03kJgpbydl5zgzT3dm+PFc33iCUFd4sq1Pc6SBeshbkaS5T65eYEQ62L6rHqDpYZpKoMuxtaAjZPpJFxdTOoVquvcIPqFCUSddznYRdWHKOWQUUiLFyEjJgfibKRelBO2ugusieEWWu+uFJBT/Ippx3+3ab51zeSbCHTntEof32T142CrGAVagZE6B/Z3TEDQ7LjG1GOR9LGXTedjsn2xjgozb6V1p+VWgofu1X4q08g7XJKSi1S/3I+wHZcVOitqooOX54s5nOBmWNT14xSFIQZ0IcG+bBmyUcc=
    bucket: magazine.beta.hevnly.com
    region: eu-west-1
    skip_cleanup: true
    acl: public_read
    local_dir: build
    on:
      branch: master
  - provider: s3
    access_key_id: AKIAJRNWPZQET66PPB5Q
    secret_access_key:
      secure: rPQc8prtSrepyAHE5qST1HTWfQnX3r8P8ahh/LwP4uVKiiujevzGHWEB5EfjHeRzLtMMAr3xyLn+xO3pHchPdK56pKLOl9Vizt11WARA2mJH1OO636zw7bsXj1y0cpFnGOcn26S3xJYRjorgPvJ4iWv10wiVVPL5kfwvmVkRpbUOdYx8BijAMDxbwPYGH1PXU7ixFOgpJIYrhCkW/2hIfdAkIufsiCtFYGAqSpKs9ogj02nEcT3yr1Et7VS0wTWKqgYrPZBUi/KjOdt/YJiNyrvqzxklCXc+7wfDdbvespyt8zR8eYstDgnVFB623poje/wBqgMDnsD4kvPHC53rpj6vyapLqkDLKo1rJ2i9G/sHrRYksX45b0YB3AyG2t4mcX+AzmtIC2IQYXIGEfKc0r4zfrfWehIFBg/CorPUP/uO2aXBcxMD8OitPLH78JKIbu5vR8g8dbXcBLFdaRmqKMjd2T6Wb9pS55lTvuIB2yY4AR3RbIvabEQIVMyqU5FEYMcb5k7Ovofz1kqtcEwMs7ryYe0H0oBSXX6GR11YTMKDiNhD+Mc1BXbfa5r6Q0oIuhZheNOlEUT04GqJ8bcxb6x5CZirmisHHZlYF+49dv5zmW04UwOKiiZQWSQKJw0TJnN1qS+Cu2DLUIPu4vhIWfw0Ju/J3peP0eIR+h1qbUE=
    bucket: magazine.nightly.hevnly.com
    region: eu-west-1
    skip_cleanup: true
    acl: public_read
    local_dir: build
    on:
      branch: develop
